source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.10"

gem "activejob-traffic_control"
gem "acts_as_tenant", "1.0.1"
gem "ahoy_matey"
gem "apnotic"
gem "aws-sdk-s3", "~> 1.227", require: false
gem "bcrypt"
gem "bootstrap", "~> 4.6.2"
gem "chartkick", ">= 3.4.0"
# Pin to 2.x — connection_pool 3.x changed ConnectionPool.new to require
# keyword args, which Rails 7.1's RedisCacheStore can't call.
gem "connection_pool", "~> 2.5"
gem "dotenv-rails", require: "dotenv/rails-now"
gem "draper"
gem "faker", :git => "https://github.com/stympy/faker.git", :branch => "master"
gem "fcm"
gem "friendly_id"
gem "groupdate"
gem "honeybadger"
gem "geocoder"
gem "httparty"
gem "icalendar"
# Used by Kisi::Client to keep a warm HTTPS connection to api.kisi.io so the
# TLS handshake isn't paid every door unlock (~300-500ms saved per unlock —
# most of the perceived gap between Face ID and the door actually opening).
gem "net-http-persistent"
gem "image_processing", "~> 1.14"
gem "importmap-rails"
gem "interactor", "~> 3.0"
gem "jbuilder", "~> 2.15"
gem "jquery-rails", ">= 4.4.0"
gem "json", ">= 2.3.0"
gem "momentjs-rails", ">= 2.9.0"
gem "money"
gem "net-http"
gem "octicons_helper"
gem "opensearch-ruby"
gem "pagy", "~> 6.0.2"
gem "pg"
gem "premailer-rails"
gem "puma", "~> 7.0"
gem "pundit"
gem "rack-attack", "~> 6.7"
gem "rack-cors"
gem "rails", "7.2.3.2"
gem "rails_autolink"
gem "redis"
gem "remotipart", "~> 1.2"
gem "request_store"
gem "sassc-rails", "~> 2.1"
gem "searchkick"
gem "sidekiq", "~> 7.3"
gem "simple_calendar"
gem "sprockets-rails"
gem "stimulus-rails"
gem "stripe", "~> 5.55.0"
gem "turbo-rails"
gem "uglifier", ">= 1.3.0"
gem "view_component"
gem "working_hours"
gem "timecop"
gem "cocoon"
gem "uri", "~> 1.1.1"

group :development do
  gem "annotate"
  gem "better_errors", ">= 2.8.0"
  gem "binding_of_caller"
  gem "listen", ">= 3.0.5", "< 3.8"
  gem "rack-mini-profiler", "~> 3.1"
  gem "rails-erd"
  gem "user-auth", git: "https://github.com/jellyswitch/user-auth", :branch => "master"
  gem "web-console", ">= 4.1.0"
end

group :test do
  gem "capybara"
  gem "ffi"
  gem "selenium-webdriver"
  gem "database_cleaner-active_record"
  gem "webmock"
  gem "shoulda-matchers"
end

group :development, :test do
  gem "bundler-audit"
  gem "debug", platforms: [:mri, :mingw, :x64_mingw]
  gem "minitest", "~> 5.0"
  gem "mocha", "~> 1.14"
  gem "policy-assertions"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rails-controller-testing"
  gem "stripe-ruby-mock", :require => "stripe_mock"
  gem "rspec-rails"
  gem "factory_bot_rails"
end
