Rails.application.config.x.customization.name = ENV['INSTANCE_NAME'] || "Bristlecone"
Rails.application.config.x.customization.snippet = ENV['INSTANCE_SNIPPET'] || "Generic snippet here"
Rails.application.config.x.customization.background = ENV['INSTANCE_BACKGROUND'] || "defaultbackground.png"
Rails.application.config.x.customization.wifi_name = ENV['WIFI_NAME'] || "not set"
Rails.application.config.x.customization.wifi_password = ENV['WIFI_PASSWORD'] || "not set"
Rails.application.config.x.customization.building_address = ENV['BUILDING_ADDRESS'] || "not set"