# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@rails/actiontext", to: "https://ga.jspm.io/npm:@rails/actiontext@7.0.3-1/app/javascript/actiontext/index.js"
pin "@rails/activestorage", to: "https://ga.jspm.io/npm:@rails/activestorage@7.0.3-1/app/assets/javascripts/activestorage.esm.js"
pin "@rails/ujs", to: "https://ga.jspm.io/npm:@rails/ujs@7.0.3-1/lib/assets/compiled/rails-ujs.js"
pin "ahoy.js", to: "https://ga.jspm.io/npm:ahoy.js@0.3.4/dist/ahoy.js"
pin "chartkick", to: "chartkick.js"
pin "Chart.bundle", to: "Chart.bundle.js"
pin "moment", to: "https://ga.jspm.io/npm:moment@2.24.0/moment.js"
pin "moment-timezone", to: "https://ga.jspm.io/npm:moment-timezone@0.5.11/index.js"
pin "rails-erb-loader", to: "https://ga.jspm.io/npm:rails-erb-loader@5.5.2/index.js"
pin "tempusdominus-bootstrap-4", to: "https://ga.jspm.io/npm:tempusdominus-bootstrap-4@5.1.2/build/js/tempusdominus-bootstrap-4.js"
pin "tempusdominus-core", to: "https://ga.jspm.io/npm:tempusdominus-core@5.0.3/build/js/tempusdominus-core.js"
pin "trix", to: "https://ga.jspm.io/npm:trix@1.2.0/dist/trix.js"
pin "big.js", to: "https://ga.jspm.io/npm:big.js@5.2.2/big.js"
pin "buffer", to: "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.26/nodelibs/browser/buffer.js"
pin "child_process", to: "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.26/nodelibs/browser/child_process.js"
pin "crypto", to: "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.26/nodelibs/browser/crypto.js"
pin "emojis-list", to: "https://ga.jspm.io/npm:emojis-list@3.0.0/index.js"
pin "fs", to: "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.26/nodelibs/browser/fs.js"
pin "json5", to: "https://ga.jspm.io/npm:json5@1.0.1/dist/index.js"
pin "loader-utils", to: "https://ga.jspm.io/npm:loader-utils@1.4.0/lib/index.js"
pin "lodash.defaults", to: "https://ga.jspm.io/npm:lodash.defaults@4.2.0/index.js"
pin "path", to: "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.26/nodelibs/browser/path.js"
pin "process", to: "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.26/nodelibs/browser/process-production.js"
pin "util", to: "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.26/nodelibs/browser/util.js"
pin "@nathanvda/cocoon", to: "https://ga.jspm.io/npm:@nathanvda/cocoon@1.2.14/cocoon.js"
pin "trix"
pin "@rails/actiontext", to: "actiontext.js"
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
pin "tributejs", to: "https://ga.jspm.io/npm:tributejs@5.1.3/dist/tribute.min.js"
pin "bootstrap", to: "https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
pin "jquery", to: "https://ga.jspm.io/npm:jquery@3.7.1/dist/jquery.js"
pin "popper.js", to: "https://ga.jspm.io/npm:popper.js@1.16.1/dist/umd/popper.js"
pin "fullcalendar", to: "https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js"
